import { MatchedVar } from "./matcher.js";

export function generateMarkdown(matched: MatchedVar[], aiDescriptions: Map<string, any>, options: { projectName: string; outputMode: string }): string {
  const categories = new Map<string, MatchedVar[]>();

  // Group by category
  for (const v of matched) {
    let category = v.category || "Other";
    let descDetails = aiDescriptions.get(v.key);
    
    if (descDetails) {
       v.description = descDetails.description || v.description;
       v.type = descDetails.type || v.type;
       v.required = descDetails.required ?? false;
       v.example = descDetails.example || v.example;
    }

    if (!v.type) v.type = "📝 String";
    if (v.required === undefined) v.required = false;

    if (!categories.has(category)) {
      categories.set(category, []);
    }
    categories.get(category)!.push(v);
  }

  let md = `# 🔧 Environment Variables — ${options.projectName}\n\n`;
  md += `> Auto-generated by [envdoc](https://npmjs.com/package/envdoc). Run \`npx envdoc\` to regenerate.\n\n`;

  const total = matched.length;
  const secrets = matched.filter(v => v.type?.toLowerCase().includes("secret")).length;
  const required = matched.filter(v => v.required).length;

  md += `**${total} variables** · **${secrets} secrets** · **${required} required**\n\n`;

  for (const [cat, vars] of categories.entries()) {
    md += `## 📦 ${cat}\n\n`;
    md += `| Variable | Description | Type | Required | Example |\n`;
    md += `|----------|-------------|------|----------|---------|\n`;
    for (const v of vars) {
      const reqStr = v.required ? "**Required**" : "Optional";
      md += `| \`${v.key}\` | ${v.description || 'No description provided.'} | ${v.type} | ${reqStr} | \`${v.example || '—'}\` |\n`;
    }
    md += "\n";
  }

  md += `---\n*Generated at ${new Date().toISOString()} by envdoc*\n`;
  return md;
}

export function generateReadmeSection(matched: MatchedVar[], aiDescriptions: Map<string, any>): string {
  let section = "<!-- envdoc:start -->\n";
  section += generateMarkdown(matched, aiDescriptions, { projectName: "Project", outputMode: "readme" });
  section += "\n<!-- envdoc:end -->";
  return section;
}
